module TokenType
  # Single-character tokens
  LEFT_BRACKET = :LEFT_BRACKET
  RIGHT_BRACKET = :RIGHT_BRACKET
  COLON = :COLON
  COMMA = :COMMA
  LEFT_ARRAY = :LEFT_ARRAY
  RIGHT_ARRAY = :RIGHT_ARRAY

  # literal
  STRING = :STRING
  NUMBER = :NUMBER
  NULL = :NULL
  BOOLEAN = :BOOLEAN
end
